version: '3'

networks:
  inspectit-world:
    driver: bridge

volumes:
  influx-data:
  influx-meta:
  cmr-config:
  cmr-ci:

services:

  cmr:
    build: ./cmr
    image: inspectit_platform/cmr
    container_name: inspectit_cmr
    restart: always
    volumes:
      - cmr-ci:/CMR/ci
      - cmr-config:/CMR/config
    networks:
      - inspectit-world
    environment:
      - BUFFER_SIZE=6000
    ports:
      - "8182:8182"
      - "9070:9070"

  cadvisor:
    image: google/cadvisor:canary
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    ports:
      - "9090:8080"
    depends_on:
      - influx
    networks:
          - inspectit-world
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    container_name: apm_cadvisor

  influx:
    build: ./influx
    image: inspectit_platform/influx
    container_name: influx
    volumes:
      - influx-data:/var/lib/influxdb/data
      - influx-meta:/var/lib/influxdb/meta
    networks:
      - inspectit-world
    environment:
      - PRE_CREATE_DB=cadvisor,inspectit
    ports:
      - "8086:8086"
      - "8083:8083"

  grafana:
    build: ./grafana
    image: inspectit_platform/grafana
    container_name: grafana
    networks:
      - inspectit-world
    ports:
      - "3000:3000"



